name: Google Tests & Coverage

on:
  push:
    paths:
      - tests/**
      
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # Pozwala na pushowanie do repozytorium
      pages: write      # Pozwala na zarządzanie GitHub Pages
      id-token: write   # Potrzebne do autoryzacji GitHub Pages
  
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov libgtest-dev gcovr
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

      - uses: actions/checkout@v3  # Pobranie kodu repozytorium

      - name: Build tests and coverage
        run: make coverage

      - name: Run tests
        run: make run_test

      - name: Generate coverage report
        run: |
         lcov --directory . --zerocounters && \
           ./tests/test_logger && \
         lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch,gcov --rc geninfo_unexecuted_blocks=1 && \
         lcov --remove coverage.info '/usr/*' 'tests/*' --output-file coverage_filtered.info && \
         genhtml coverage_filtered.info --output-directory coverage_report

      - name: Deploy coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # Gałąź, na którą pushujemy
          folder: coverage_report  # Katalog z plikami do publikacji
          clean: true  # Usuwa stare pliki przed publikacją
          
      - name: Generate coverage badge
        run: |
            COVERAGE=$(lcov --summary coverage_filtered.info | grep "lines" | awk '{print $2}' | tr -d '%')
            echo "{ \"schemaVersion\": 1, \"label\": \"coverage\", \"message\": \"$COVERAGE%\", \"color\": \"green\" }" > coverage.json
    
      - name: Deploy coverage badge
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            branch: gh-pages
            folder: .
            target-folder: coverage
